# ** Used for running this lambda locally **
# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  eventSubscriber
Transform:
- AWS::Serverless-2016-10-31
Resources:
  EventSubscriber:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that logs the time to notification from an SNS mesage
      Runtime: nodejs10.x
      Handler: dist/app.handler
      Environment:
        Variables:
          NOTIFICATIONS_BUCKET:
          NOTIFICATIONS_KEY:
          TIMEOUT_S3:
      MemorySize: 128
      Timeout: 25 # Chosen to be less than the default SQS Visibility Timeout of 30 seconds
